name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY

      - name: Build Docker image
        run: docker build -t $ECR_REPOSITORY:$GITHUB_SHA .

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPOSITORY:$GITHUB_SHA

env:
  ECR_REPOSITORY: 590183892056.dkr.ecr.ap-south-1.amazonaws.com/sdc-api  # Replace with your ECR repository URI
